# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c172a3934a4fd01180c3dd1163a31324f115bb6e48d1e6ea654e05d2bdc272d13e8b2878b9e048335640a65d74aef7686799599ff1f80265a927d96ac471c1d

test:
  secret_key_base: 7ba0a28f616bb480eea53a82913307c5a66e2cb6d0b9eff9c43e8ffded948559fb91851c7b25863b0c6fe21d8d048f5250f08f8d851960c3bdf3909a1b8c5a28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
